services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: predictive-maintenance-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped